-- Employer profile table used by Auth/SignUp.php.
-- Existing Supabase project already has this schema; this file records it for setup elsewhere.
CREATE TABLE IF NOT EXISTS public.employers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL UNIQUE REFERENCES public.users(id) ON DELETE CASCADE,
    company_name text NOT NULL,
    contact_number text NULL
);

-- Keep public Data API clients from reading or writing profiles without a policy.
ALTER TABLE public.employers ENABLE ROW LEVEL SECURITY;
